name: Push workflow

on: [push]

jobs:
  tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jest run
        run: yarn test:unit
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: yarn build
          start: yarn start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}